spring:
  application:
    name: day06-intergration
  ai:
    google:
      genai:
        chat:
          model: gemini-3.1-flash-lite
        api-key: ${GOOGLE_API_KEY}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    error:
      include-message: always
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: helpdesk
    password: helpdesk
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

